/* Generated by firmware/tools/make_display_assets.py. Do not edit by hand. */

#ifndef DISPLAY_ASSETS_H
#define DISPLAY_ASSETS_H

#include "display/canvas.h"

// The degree sign is stored as character code 0x7F.
#define DISPLAY_DEGREE "\x7F"

extern const canvas_font_t font_value;   // DejaVuSans.ttf 34px, 25 px tall
extern const canvas_font_t font_unit;   // DejaVuSans.ttf 15px, 16 px tall
extern const canvas_font_t font_label;   // DejaVuSans-Bold.ttf 10px, 10 px tall

extern const canvas_bitmap_t icon_temperature;
extern const canvas_bitmap_t icon_humidity;
extern const canvas_bitmap_t icon_light;
extern const canvas_bitmap_t icon_uv;
extern const canvas_bitmap_t icon_magnet;
extern const canvas_bitmap_t icon_supply;
extern const canvas_bitmap_t icon_chip;
extern const canvas_bitmap_t icon_orientation;
extern const canvas_bitmap_t icon_button;
extern const canvas_bitmap_t icon_sound;
extern const canvas_bitmap_t icon_bluetooth;

#endif // DISPLAY_ASSETS_H
