#!/usr/bin/env python3
"""Generates the OLED display's fonts and icons as C arrays.

Output: firmware/src/display/display_assets.c and display_assets.h
(both committed, so building the firmware never needs Python).

Run again only after changing a font, size, character set or icon here:
    python3 firmware/tools/make_display_assets.py

Needs Pillow (python3-pil) and the DejaVu fonts (Ubuntu: fonts-dejavu-core),
which are free to embed (Bitstream Vera / DejaVu license).

Bitmap format (shared with src/display/canvas.c):
  every glyph/icon is stored row by row, each row padded to whole bytes,
  most significant bit = leftmost pixel, 1 = lit.
"""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

FONT_DIR = Path("/usr/share/fonts/truetype/dejavu")
OUT_DIR = Path(__file__).resolve().parent.parent / "src" / "display"

DEGREE = "°"          # stored as char code 0x7F ("DEL") in the fonts
ASCII = "".join(chr(c) for c in range(32, 127)) + DEGREE

# name, TTF file, pixel size, characters
FONTS = [
    ("font_value", "DejaVuSans.ttf", 34, "0123456789.-+"),        # the big number
    ("font_unit", "DejaVuSans.ttf", 15, ASCII),                    # units, orientation rows
    ("font_label", "DejaVuSans-Bold.ttf", 10, ASCII),              # titles
]

# 16x16 icons, '#' = lit pixel. Edit freely; keep 16 columns x 16 rows.
ICONS = {
    "icon_temperature": """
        ......##........
        .....#..#.......
        .....#..#..###..
        .....#..#.......
        .....#..#..##...
        .....#..#.......
        .....####..###..
        .....####.......
        .....####..##...
        ....######......
        ...########.....
        ...########.....
        ...########.....
        ....######......
        .....####.......
        ................""",
    "icon_humidity": """
        .......#........
        .......#........
        ......###.......
        ......###.......
        .....#####......
        ....#######.....
        ....#######.....
        ...#########....
        ...#######.#....
        ..########.##...
        ..########.##...
        ..#######.###...
        ...#####.###....
        ....#######.....
        ......###.......
        ................""",
    "icon_light": """
        .......#........
        ..#....#....#...
        ...#.......#....
        ......###.......
        ....#######.....
        ....#######.....
        ...#########....
        ##.#########.##.
        ...#########....
        ....#######.....
        ....#######.....
        ......###.......
        ...#.......#....
        ..#....#....#...
        .......#........
        ................""",
    "icon_uv": """
        ................
        ..#....#....#...
        ...#...#...#....
        ................
        .#.#.#..#...#...
        .#.#.#..#...#...
        .#.#.#..#...#...
        .#.#.#...#.#....
        .#.#.#...#.#....
        .#.#.#...#.#....
        ..#.#.....#.....
        ................
        ...#...#...#....
        ..#....#....#...
        ................
        ................""",
    "icon_magnet": """
        ................
        ...####..####...
        ..#####..#####..
        .######..######.
        .###........###.
        .###........###.
        .###........###.
        .###........###.
        .###........###.
        .####......####.
        ..####....####..
        ...##########...
        ....########....
        ......####......
        ................
        ................""",
    "icon_supply": """
        .........##.....
        ........##......
        .......###......
        ......###.......
        .....###........
        ....#########...
        ...#########....
        ........###.....
        .......###......
        ......###.......
        .....###........
        .....##.........
        ....##..........
        ....#...........
        ................
        ................""",
    "icon_chip": """
        ...#.#.#.#.#....
        ...#.#.#.#.#....
        .###########....
        .#.........#....
        ##.#######.###..
        .#.#.....#.#....
        ##.#.....#.###..
        .#.#.....#.#....
        ##.#######.###..
        .#.........#....
        .###########....
        ...#.#.#.#.#....
        ...#.#.#.#.#....
        ................
        ................
        ................""",
    "icon_orientation": """
        .......#........
        ......###.......
        .....#.#.#......
        .......#........
        .......#........
        .......#........
        .......#........
        ......###.......
        .....#####......
        ....##...##.....
        ...##.....##....
        ..##.......##...
        .###.......###..
        ................
        ................
        ................""",
    "icon_button": """
        ................
        ....########....
        ...##......##...
        ..##..####..##..
        ..#..######..#..
        ..#.########.#..
        ..#.########.#..
        ..#.########.#..
        ..#.########.#..
        ..#..######..#..
        ..##..####..##..
        ...##......##...
        ....########....
        ................
        ................
        ................""",
    "icon_sound": """
        ................
        .....#......#...
        ....##...#...#..
        ...###....#..#..
        ######..#..#..#.
        ######...#.#..#.
        ######...#.#..#.
        ######...#.#..#.
        ######..#..#..#.
        ...###....#..#..
        ....##...#...#..
        .....#......#...
        ................
        ................
        ................
        ................""",
    "icon_bluetooth": """
        ......#.........
        ......##........
        ......#.#.......
        ..#...#..#......
        ...#..#.#.......
        ....#.##........
        .....##.........
        ....#.##........
        ...#..#.#.......
        ..#...#..#......
        ......#.#.......
        ......##........
        ......#.........
        ................
        ................
        ................""",
}


def pack_rows(rows):
    """rows: list of lists of 0/1 -> bytes, row-major, each row padded to bytes."""
    out = []
    for row in rows:
        for i in range(0, len(row), 8):
            byte = 0
            for bit, v in enumerate(row[i:i + 8]):
                if v:
                    byte |= 0x80 >> bit
            out.append(byte)
    return out


def render_font(name, ttf, size, chars):
    font = ImageFont.truetype(str(FONT_DIR / ttf), size)
    ascent, descent = font.getmetrics()
    glyphs = []
    for ch in chars:
        width = max(1, round(font.getlength(ch)))
        image = Image.new("L", (width, ascent + descent), 0)
        ImageDraw.Draw(image).text((0, 0), ch, font=font, fill=255)
        glyphs.append((ch, width, image))

    # Crop the rows no glyph uses, so fonts take less flash and no
    # vertical space on the screen is wasted.
    top, bottom = ascent + descent, 0
    for _, _, image in glyphs:
        box = image.getbbox()
        if box:
            top = min(top, box[1])
            bottom = max(bottom, box[3])
    height = bottom - top

    data, table = [], []
    for ch, width, image in glyphs:
        rows = [[1 if image.getpixel((x, y)) >= 128 else 0 for x in range(width)] for y in range(top, bottom)]
        table.append((ch, width, len(data)))
        data += pack_rows(rows)
    return height, table, data


def char_literal(ch):
    code = 0x7F if ch == DEGREE else ord(ch)
    return f"0x{code:02X}"


def main():
    c = ['/* Generated by firmware/tools/make_display_assets.py. Do not edit by hand. */',
         '', '#include "display/display_assets.h"', '']
    h = ['/* Generated by firmware/tools/make_display_assets.py. Do not edit by hand. */',
         '', '#ifndef DISPLAY_ASSETS_H', '#define DISPLAY_ASSETS_H', '',
         '#include "display/canvas.h"', '',
         '// The degree sign is stored as character code 0x7F.',
         '#define DISPLAY_DEGREE "\\x7F"', '']

    for name, ttf, size, chars in FONTS:
        height, table, data = render_font(name, ttf, size, chars)
        c.append(f"// {ttf} {size}px, {len(table)} glyphs, {height} px tall")
        c.append(f"static const uint8_t {name}_bitmaps[] = {{")
        for i in range(0, len(data), 16):
            c.append("  " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",")
        c.append("};")
        c.append(f"static const canvas_glyph_t {name}_glyphs[] = {{")
        for ch, width, offset in table:
            c.append(f"  {{ {char_literal(ch)}, {width}, {offset} }},")
        c.append("};")
        c.append(f"const canvas_font_t {name} = {{ {height}, {len(table)}, {name}_glyphs, {name}_bitmaps }};")
        c.append("")
        h.append(f"extern const canvas_font_t {name};   // {ttf} {size}px, {height} px tall")

    h.append("")
    for name, art in ICONS.items():
        rows = [[1 if ch == "#" else 0 for ch in line.strip()] for line in art.strip().splitlines()]
        assert len(rows) == 16 and all(len(r) == 16 for r in rows), f"{name} must be 16x16"
        data = pack_rows(rows)
        c.append(f"static const uint8_t {name}_bits[] = {{ " + ", ".join(f"0x{b:02X}" for b in data) + " };")
        c.append(f"const canvas_bitmap_t {name} = {{ 16, 16, {name}_bits }};")
        h.append(f"extern const canvas_bitmap_t {name};")

    h += ["", "#endif // DISPLAY_ASSETS_H", ""]
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "display_assets.c").write_text("\n".join(c) + "\n")
    (OUT_DIR / "display_assets.h").write_text("\n".join(h))
    print(f"wrote {OUT_DIR / 'display_assets.c'} and display_assets.h")


if __name__ == "__main__":
    main()
